sonar.projectKey=request
sonar.projectName=request
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=my_tests
sonar.exclusions=my_tests/*
sonar.python.coverage.reportPaths=coverage.xml
sonar.token=sqp_7702074b077abf8087d45c84cc70cc2a61b52dcf

